name: test build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.txt'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      -
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine m2r

      - name: Build and publish
        run: |
          ./test_build.sh
